# Generated by Django 3.0.5 on 2020-05-14 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_amizade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amigos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myid', models.IntegerField(verbose_name=django.db.models.deletion.DO_NOTHING)),
                ('amigo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.AuthUser')),
            ],
        ),
    ]
