# Generated by Django 3.0.5 on 2020-05-14 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_amigos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amigos',
            name='myid',
            field=models.IntegerField(),
        ),
    ]
