# Generated by Django 3.0.5 on 2020-06-03 01:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_amigos_data_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='amizade',
            name='data_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amizade',
            name='myUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user1', to='app.AuthUser'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='amizade',
            name='amigo',
        ),
        migrations.AddField(
            model_name='amizade',
            name='amigo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user2', to='app.AuthUser'),
            preserve_default=False,
        ),
    ]
